name: 'Release Notes Pronto Notification Action'
description: 'Send a Pronto message with release notes for a new deployment'
inputs:
  chat-id:
    description: "The ID of the Pronto chat in which to send the message."
    required: true
  max-commits:
    description: "Maximum number of commit messages to include. Defaults to 10."
    required: false
  github-api-token:
    description: "The Github API token used to make API requests"
    required: true
  pronto-api-token:
    description: "The Pronto API token used to make API requests"
    required: true
  api-domain:
    description: "The domain of the Pronto server. Defaults to 'api.pronto.io'."
    required: false
runs:
  using: 'node20'
  main: 'index.js'